version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: db_name
